on:
  push:

defaults:
  run:
    shell: bash

jobs:
  python-artifact:
    runs-on: ubuntu-latest
    name: "python-artifact"

    env:
      CR_PAT: ${{ secrets.CR_PAT }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build
      run: |
        docker build -t artifact-python-demo .
        docker tag ghcr.io/srnatan/ci-cd-artifact-python/artifact-python-demo:latest artifact-python-demo

    - name: Deploy
      #el echo $CR_PAT está en la documentación de https://docs.github.com/es/packages/working-with-a-github-packages-registry/working-with-the-container-registry
      run: |
        $ echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
        docker push ghcr.io/srnatan/ci-cd-artifact-python/artifact-python-demo:latest
